import {store} from './store/store.js'

// add this to index.js: import('./devDataMock.js').catch(logger.error)

/* eslint-disable */
setTimeout(() => {
  console.log('running devDataMock')
  store.createFolder('folder 1')
  store.createFolder('folder 2')
  store.createFolder('folder 3')
  store.addSubreddit('Aww')
  store.addSubreddit('Cute')
  store.addSubreddit('Foxes')
  store.addSubreddit('CatGifs')
  store.addSubreddit('Pics')
  store.addSubreddit('Space')
  store.addSubreddit('Abandoned')
  store.addSubreddit('Animals')
  store.addSubreddit('Cats')
  store.addSubreddit('RedPandas')
  store.addSubreddit('HardcoreAww')
  store.addSubreddit('CatsStandingUp')
  store.addSubreddit('Photography')
  store.addSubreddit('Gifs')
  store.addSubreddit('Future')
  store.addSubreddit('Maps')
  store.addSubreddit('Puppies')
  store.addSubreddit('Rabbits')
  store.addSubreddit('DogPictures')
  store.addSubreddit('Earth')
  store.addSubreddit('HDR')
  store.addSubreddit('Food')
  store.addSubreddit('Art')
  store.addFavouriteSubreddit('Pics')
  store.addFavouriteSubreddit('Space')
  store.addFavouriteSubreddit('Abandoned')
  store.addFavouriteSubreddit('Animals')
  store.addFavouriteSubreddit('Cats') 
}, 3000)